### ISSUE TITLE
乱七八糟的药水效果

### ISSUE THREAD

**Issue by INV-PLA** [thexaero/xaero-minimap-translations#13]
And [PolyMc] https://github.com/TheEpicBlock/PolyMc, if you have a custom potion effect module, map would be considered to disable the map function potion effect

**Comment by INV-PLA** [comment]
May I ask how it was repaired?

**Comment by thexaero** [comment]
This isn't an issue tracker for the minimap mod. I also have no idea what you're trying to report.
