### ISSUE TITLE
Xaero's Minimap save path problem

### ISSUE THREAD

**Issue by PatricianEagle** [thexaero/xaero-minimap-translations#22]
Sorry, I don't know where to report bugs.

 I'm having some problems with Xaero's Minimap module. I want to rely on the HMCl launcher to update client data.

But the program reported an error.
![2](https://github.com/user-attachments/assets/f5e9dfb9-eb7c-41e5-afe8-861e2ca35b1c)

I think the %0 in the path('overrides/xaero/minimap/Multiplayer/dim%0/mw$1490030259_1.txt') is causing the URL to fail to resolve.
I want to remove % from this path. What should I do.

**Comment by thexaero** [comment]
This isn't the place to report bugs for the minimap mod and this isn't a bug in the minimap mod in the first place.
